### Testing - GET
GET http://localhost:5000/test/start
content-type: application/json



### Testing - GET
GET http://localhost:5000/test/nodecashe
content-type: application/json



### Testing - GET
GET http://localhost:5000/test/redis
content-type: application/json